-- Part 1: Create custom types
CREATE TYPE "Role" AS ENUM ('ADMIN', 'USER');

CREATE TYPE "AnalysisType" AS ENUM (
  'DESCRIPTIVE_STATS',
  'TREND_ANALYSIS', 
  'CONTENT_ANALYSIS',
  'THEMATIC_ANALYSIS',
  'CORRELATION_ANALYSIS',
  'SURVEY_NOTE_ANALYSIS',
  'NEWS_SCRAPING_ANALYSIS',
  'FENOMENA_INSIGHTS',
  'CORRELATION_MATRIX'
);